name: Tag
on:
  push:
    tags: [v*.*.*]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        run: | # build and push it with the tag created on the repo
          committed_tag=${GITHUB_REF#refs/*/}
          TAG=$(basename "${committed_tag}")
          docker buildx build --platform linux/amd64 -t ghcr.io/${{ github.repository_owner }}/alaz:${TAG} --push .
